use_frameworks!

pod 'Parse'
pod 'ParseUI'
pod 'ParseFacebookUtilsV4'
pod 'FBSDKCoreKit'
pod 'FBSDKLoginKit'
pod 'FBSDKShareKit'
pod 'AFNetworking'
pod 'RESideMenu'
pod 'RAMAnimatedTabBarController'

